import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        forest: {
          50: "#f0f7f2",
          100: "#dceee1",
          200: "#baddc5",
          300: "#8cc5a0",
          400: "#5da878",
          500: "#3d8c5c",
          600: "#2d7049",
          700: "#245a3c",
          800: "#1f4831",
          900: "#1a3c2a",
          950: "#0d2118",
        },
        cream: {
          50: "#fefdfb",
          100: "#faf6f0",
          200: "#f5ede0",
          300: "#ede0cc",
          400: "#e2cdb0",
          500: "#d4b48e",
        },
        "primary": "#1a3c2a",
        "primary-container": "#245a3c",
        "secondary": "#b02f00",
        "secondary-container": "#ff5722",
        "surface": "#faf6f0",
        "on-surface": "#1a1a1a",
        "on-surface-variant": "#555555",
        "outline": "#999999",
        "outline-variant": "#e0d8ce",
        "surface-container-low": "#f5ede0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ede0cc",
        "surface-container": "#f5ede0",
        "surface-variant": "#e8e0d4",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#1a3c2a",
        "inverse-on-surface": "#f0f7f2",
        "on-primary-container": "#dceee1",
        "on-secondary-container": "#541100",
        "surface-bright": "#faf6f0",
        "surface-dim": "#ede0cc",
        "surface-container-highest": "#e2cdb0",
        "on-background": "#1a1a1a",
        "background": "#faf6f0",
        "tertiary": "#8B6914",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["Playfair Display", "serif"],
        body: ["DM Sans", "sans-serif"],
        label: ["DM Sans", "sans-serif"],
        script: ["Cormorant Garant", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      animation: {
        "fade-in": "fadeIn 0.8s ease-out forwards",
        "slide-up": "slideUp 0.6s ease-out forwards",
        "float": "float 6s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
